# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: person.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'person.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cperson.proto\x12\x06person\"\x1d\n\x0fPersonIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"Y\n\x0ePersonResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t2Q\n\rPersonService\x12@\n\rGetPersonById\x12\x17.person.PersonIdRequest\x1a\x16.person.PersonResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'person_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSONIDREQUEST']._serialized_start=24
  _globals['_PERSONIDREQUEST']._serialized_end=53
  _globals['_PERSONRESPONSE']._serialized_start=55
  _globals['_PERSONRESPONSE']._serialized_end=144
  _globals['_PERSONSERVICE']._serialized_start=146
  _globals['_PERSONSERVICE']._serialized_end=227
# @@protoc_insertion_point(module_scope)
